INSERT INTO [dbo].[Position] ([PositionId], [PositionName], [PositionDescription], [PayPeriod], [PayRate]) VALUES(N'1', N'Helpdesk Advisor', N'Works on the helpdesk ', N'H', N'$'),
(N'2', N'Administrative Clerk', N'Provides administrative support', N'H', N'$'),
(N'3', N'HR Clerk', N'Provides support to the Market', N'H', N'$'),
(N'4', N'Finance Clerk', N'Provides support to the Finan', N'H', N'$'),
(N'5', N'Marketing Assistant', N'Provides support to the Market', N'H', N'$'),
(N'6', N'Social Media Assistant', N' Provides support to the Socia', N'H', N'$'),
(N'7', N'Assistant', N'Works  in any number of areas', N'H', N'$'),
(N'8', N'Workforce Support', N' Provides support to the Workflow', N'H', N'$'),
(N'9', N'CEO', N' Chief Executive Officer', N'Y', N'$'),
(N'10', N'Volunteer Coordinator', N' Coordinates  recruitment', N'H', N'$'),
(N'11', N'Sponsorship Coordinator', N'Identifies, develops and main', N'Y', N'$'),
(N'13', N'Social Media Coordinator', N'Manages content across social', N'Y', N'$'),
(N'14', N'Operations Manager', N'Oversees all logistical aspects', N'Y', N'$'),
(N'16', N'IT Manager', N'Oversees the plannin', N'Y', N'$'),
(N'19', N'Administrative Manager', N' Oversees the administrative flow', N'Y', N'$'),
(N'20', N'HR Manager', N'Manages the recruitment, reted', N'Y', N'$'),
(N'21', N'Finance Manager', N'esponsible for the financial', N'Y', N'$'),
(N'23', N'Workforce Manager', N'Responsible for coordinating', N'Y', N'$');
